SELECT NUNOTA
FROM TGFCAB
WHERE CODTIPOPER IN (
    SELECT DISTINCT CODTIPOPER FROM TGFTOP
    WHERE CODTIPOPER IN (
        SELECT DISTINCT CAB.CODTIPOPER
        FROM TGFCAB CAB
        INNER JOIN TGFNFE NFE ON CAB.NUNOTA = NFE.NUNOTA
        WHERE CONVERT(DATE, CAB.DTNEG) = CONVERT(DATE, GETDATE())
        AND NFE.XML IS NOT NULL
    )
    AND TIPMOV = 'V'
    AND ATUALEST = 'B'
    AND ATUALFIN = 1
)
AND CHAVENFE IS NOT NULL
AND CONVERT(DATE, DTNEG) = CONVERT(DATE, GETDATE());